name: an3am
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_tawkto: ^0.0.5
  flutter_inappwebview: ^6.1.5
  flutter_speed_dial: ^7.0.0
  url_launcher: ^6.1.11
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.5.4
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  flutter_paytabs_bridge: ^2.6.7
  flutter_svg: ^2.0.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.2
  shared_preferences: ^2.2.2
  dio: ^5.1.2
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  path: ^1.8.2
  google_sign_in: ^6.2.1
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.0
  rename: ^3.0.2
  equatable: ^2.0.5
  jiffy: ^6.2.1
  dartz: ^0.10.1
  get_it: ^8.0.3
  flutter_local_notifications: ^18.0.1
  lottie: ^3.3.1
  easy_localization: ^3.0.2
  fluttertoast: ^8.2.2
  twitter_login: any
  geocoding: ^3.0.0
  sign_in_with_apple: ^6.1.0
  google_maps_flutter: ^2.5.0
  geolocator: ^13.0.2
  flutter_phoenix: ^1.1.1
  custom_info_window: ^1.0.1
  flutter_facebook_auth: ^7.1.1
  facebook_auth_desktop: ^2.1.1
  pusher_channels_flutter: ^2.2.1
#  firebase_dynamic_links: ^6.1.1
  share_plus: ^10.1.4
  font_awesome_flutter: ^10.8.0
flutter_facebook_auth:
  platforms:
    macos:
      default_package: facebook_auth_desktop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/
  fonts:
    - family: boutrosAsma
      fonts:
        - asset: assets/fonts/boutrosAsma.ttf
